### ISSUE TITLE
Package does not build for Go versions between 1.13 and 1.16

### ISSUE THREAD

**Issue by pellared** [fatih/color#183]
It looks like the newest version does not support Go versions between 1.13 and 1.16.

```
# golang.org/x/sys/unix
Error: ../../../go/pkg/mod/golang.org/x/sys@v0.3.0/unix/syscall.go:83:16: undefined: unsafe.Slice
Error: ../../../go/pkg/mod/golang.org/x/sys@v0.3.0/unix/syscall_linux.go:2[25](https://github.com/goyek/x/actions/runs/3987232497/jobs/6836778533#step:4:26)6:9: undefined: unsafe.Slice
Error: ../../../go/pkg/mod/golang.org/x/sys@v0.3.0/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
Error: ../../../go/pkg/mod/golang.org/x/sys@v0.3.0/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
note: module requires Go 1.17
```

Possible fixes:
- Change in go.mod to require Go 1.17 https://github.com/fatih/color/blob/212f8c559a38806774080f4a233040da99c11860/go.mod#L3
- Downgrade the dependencies so that it can work with Go 1.13

Personally, I think it is OK to bump to Go 1.17 as this is the oldest supported Go version.

Reference:
- https://github.com/goyek/x/actions/runs/3987232497
- https://github.com/goyek/x/pull/20

**Comment by fatih** [comment]
> Downgrade the dependencies so that it can work with Go 1.13

That's not something I'm willing to do. The dependencies have bug fixes and it's safe for everyone to move forward. Best is to bump the Go version in the go.mod file.

**Comment by pellared** [comment]
> > Downgrade the dependencies so that it can work with Go 1.13
> 
> That's not something I'm willing to do. The dependencies have bug fixes and it's safe for everyone to move forward. Best is to bump the Go version in the go.mod file.

I agree. I created a PR for you 😉

**Comment by fatih** [comment]
I cut a new release https://github.com/fatih/color/releases/tag/v1.14.1. Thanks for bringing it up.
